import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./homepage/navbar";
import FooterSection from "./homepage/footer";
import WhatsAppButton from "./homepage/whatsapp";
import ChatButton from "./homepage/chatboat";
import Header from "./homepage/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Best Web & App Design & Development Company in India",
  description: "Generated by virtualseoweb",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Header />
        <hr />
        <Navbar />
        <main>{children}</main>
        <FooterSection />
        <WhatsAppButton />
        <ChatButton />
      </body>
    </html>
  );
}